(defvar *operations*
  (let ((table (make-hash-table :test #'equal)))
    (prog1 table
           (mapcar (lambda (item)
                     (destructuring-bind (mnemonic &optional (help "") pseudop) item
                       (setf (gethash mnemonic table)
                             (make-operation :mnemonic mnemonic
                                             :pseudop pseudop
                                             :help (if pseudop
                                                       (format nil "~A (assembler pseudo-operation)" help)
                                                       help)))))
                   '(;("   ")
                     ;("")
                     ;(" ")
                     ("***")
                     ("ACL" "Add and Carry Logical Word")
                     ("ABS" "Absolute assembly" t)
                     ("ADD" "Add")
                     ("AST" "Add Symbol Table" t)
                     ("PST" "Put Symbol Table" t)
                     ("WST" "Write Symbol Table" t)
                     ("RST" "Read Symbol Table" t)
                     ("ADM" "Add Magnitude")
                     ("ALS" "Accumulator Left Shift")
                     ("ANA" "AND to Accumulator")
                     ("ANS" "AND to Storage")
                     ("ARS" "Accumulator Right Shift")
                     ("AXC" "Address to Index Complemented")
                     ("AXT" "Address to Index True")
                     ("BCD" "Binary-coded Decimal" t)
                     ("BCI" "Binary-coded Information" t)
                     ("BES" "Block Ended by Symbol" t)
                     ("BOOL" "Boolean data" t)
                     ("BSF" "Backspace File")
                     ("BSR" "Backspace Record")
                     ("BSRA" "Backspace Record Channel A")
                     ("BSS" "Block Started By Symbol" t)
                     ("BST" "Backspace Tape")
                     ("BTT" "Beginning of Tape Test")
                     ("CAD")
                     ("CAL" "Clear and Add Logical Word")
                     ("CAQ" "Convert by Addition from MQ")
                     ("CAS" "Compare Accumulator with Storage")
                     ("CFF")
                     ("CHS" "Change Sign")
                     ("CLA" "Clear and Add")
                     ("CLM" "Clear Magnitude")
                     ("CLS" "Clear and Subtract")
                     ("COM" "Complement Magnitude")
                     ("COUNT" "Estimate of Card Count" t)
                     ("CPY" "Copy and Skip")
                     ("CRQ" "Convert by Replacement from MQ")
                     ("CVR" "Convert by Replacement from Accumulator")
                     ("DCT" "Divide Check Test")
                     ("DEC" "Decimal Data" t)
                     ("DFAD" "Double-Precision Floating-Point Add")
                     ("DFAM" "Double-Precision Floating-Point Add Magnitude")
                     ("DFDH" "Double-Precision Floating-Point Divide or Halt")
                     ("DFDP" "Double-Precision Floating-Point Divide or Proceed")
                     ("DFMP" "Double-Precision Floating-Point Multiply")
                     ("DFSB" "Double-Precision Floating-Point Subtract")
                     ("DFSM" "Double-Precision Floating-Point Subtract Magnitude")
                     ("DLD" "Double Load")
                     ("DST" "Double Store")
                     ("DUAM" "Double-Precision Unnormalized Floating-Point Add Magnitude")
                     ("DUFA" "Double-Precision Unnormalized Floating-Point Add")
                     ("DUFM" "Double-Precision Unnormalized Floating-Point Multiply")
                     ("DUFS" "Double-Precision Unnormalized Floating-Point Subtract")
                     ("DUP" "Duplicate Cards" t)
                     ("DUSM" "Double-Precision Unnormalized Floating-Point Subtract Magnitude")
                     ("DVH" "Divide or Halt")
                     ("DVP" "Divide or Proceed")
                     ("ECTM" "Enter Copy Trap Mode")
                     ("EFTM" "Enter Floating Trap Mode")
                     ("EJECT" "End Page of Listing" t)
                     ("EMTM" "Enter Multiple Tag Mode")
                     ("ENB" "Enable from Y")
                     ("END" "End of Assembly" t)
                     ("ENK" "Enter Keys")
                     ("EQU" "Define Symbol" t)
                     ("ERA" "Exclusive OR to Accumulator")
                     ("ESNT" "Enter Storage Nullification and Transfer")
                     ("ESTM" "Enter Select Trap Mode")
                     ("ETC" "Continuation Card" t)
                     ("ETM" "Enter Trapping Mode")
                     ("ETT" "End of Tape Test")
                     ("EVEN" "Align to Even Address" t)
                     ("FAD" "Floating Add")
                     ("FAM" "Floating Multiply")
                     ("FDH" "Floating Divide or Halt")
                     ("FDP" "Floating Divide or Proceed")
                     ("FMP" "Floating Multiply")
                     ("FRN" "Floating Round")
                     ("FSB" "Floating Subtract")
                     ("FSM" "Floating Subtract Magnitude")
                     ("FUL" "Set Binary Output Mode" t)
                     ("HEAD" "Head Symbols" t)
                     ("HED" "Head Symbols" t)
                     ("HPR" "Halt and Proceed")
                     ("HTR" "Halt and Transfer")
                     ("IIA" "Invert Indicators from Accumulator")
                     ("IIL" "Invert Indicators of Left Half")
                     ("IIR" "Invert Indicators of Right Half")
                     ("IIS" "Invert Indicators from Storage")
                     ("INDEX" "Enable Indexing" t)
                     ("IOCD" "I/O Under Count Control and Disconnect")
                     ("IOCDN" "I/O Under Count Control and Disconnect, Non-transmitting")
                     ("IOCP" "I/O Under Count Control and Proceed")
                     ("IOCPN" "I/O Under Count Control and Proceed, Non-transmitting")
                     ("IOCT" "I/O Under Count Control and Terminate")
                     ("IOCTN" "I/O Under Count Control and Terminate, Non-transmitting")
                     ("IOD" "???")
                     ("IORP" "I/O Under Buffer Control and Proceed")
                     ("IORPN" "I/O Under Buffer Control and Proceed, Non-transmitting")
                     ("IORT" "I/O Under Buffer Control and Terminate")
                     ("IORTN" "I/O Under Buffer Control and Terminate")
                     ("IOSP" "I/O Under Special Control and Proceed")
                     ("IOSPN" "I/O Under Special Control and Proceed, Non-transmitting")
                     ("IOST" "I/O Under Special Control and Terminate")
                     ("IOSTN" "I/O Under Special Control and Terminate, Non-transmitting")
                     ("IOT" "Input-Output Check Test")
                     ("LAC" "Load Complement of Address in Storage")
                     ("LAR")
                     ("LAS" "Logical Compare Accumulator with Storage")
                     ("LAXM")
                     ("LBT" "Low-Order Bit Test")
                     ("LCHA" "Load Channel A")
                     ("LCHB" "Load Channel B")
                     ("LCHC" "Load Channel C")
                     ("LCHD" "Load Channel D")
                     ("LCHE" "Load Channel E")
                     ("LCHF" "Load Channel F")
                     ("LCHG" "Load Channel G")
                     ("LCHH" "Load Channel H")
                     ("LDA" "Locate Drum Address")
                     ("LDC" "Load Complement of Decrement in Index")
                     ("LDI" "Load Indicators")
                     ("LDQ" "Load MQ")
                     ("LFT" "Left Half Indicators OFF Test")
                     ("LFTM" "Leave Floating Trap Mode")
                     ("LGL" "Logical Left Shift")
                     ("LGR" "Logical Right Shift")
                     ("LIST" "Enable Listing" t)
                     ("LLS" "Long Left Shift")
                     ("LMTM" "Leave Multiple Tag Mode")
                     ("LNT" "Left Half Indicators ON Test")
                     ("LOC" "Set Location Counter" t)
                     ("LRS" "Long Right Shift")
                     ("LSNM" "Leave Storage Nullification Mode")
                     ("LTM" "Leave Trapping Mode")
                     ("LXA" "Load Index from Address")
                     ("LXD" "Load Index from Decrement")
                     ("MPR" "Multiply and Round")
                     ("MPY" "Multiply")
                     ("MSE" "Minus Sense")
                     ("MTH" "Minus Three")
                     ("MZE" "Minus Zero")
                     ("NOP" "No Operation")
                     ("NTR")
                     ("NULL" "Define as Location Counter" t)
                     ("NZT" "Storage Not-Zero Test")
                     ("OAI" "OR Accumulator to Indicators")
                     ("OCT" "Octal Data" t)
                     ("OFT" "Off Test for Indicators")
                     ("ONT" "On Test for Indicators")
                     ("OPD" "Define Operation" t)
                     ("OPSYN" "Define Operation Synonym" t)
                     ("OPVFD" "Define Operation Synonym Using Variable-width Field Data" t)
                     ("ORA" "OR to Accumulator")
                     ("ORG" "Set Origin" t)
                     ("ORS" "OR to Storage")
                     ("OSI" "OR Storage to Indicators")
                     ("PAC" "Place Complement of Address in Index")
                     ("PAI" "Place Accumulator in Indicators")
                     ("PAX" "Place Address in Index")
                     ("PBT" "P-bit Test")
                     ("PCA" "Place Complement of Index in Address")
                     ("PCC" "Print Control Cards" t)
                     ("PCD" "Place Complement of Index in Decrement")
                     ("PDC" "Place Complement of Decrement in Index")
                     ("PDX" "Place Decrement in Index")
                     ("PIA" "Place Indicator in Accumulator")
                     ("PON" "Positive One")
                     ("PSE" "Plus Sense")
                     ("PSLA")
                     ("PSLB")
                     ("PSLC")
                     ("PSLD")
                     ("PSLE")
                     ("PSLF")
                     ("PSLG")
                     ("PSLH")
                     ("PTH" "Positive Three")
                     ("PTW" "Positive Two")
                     ("PXA" "Place Index in Address")
                     ("PXD" "Place Index in Decrement")
                     ("PZE" "Positive Zero")
                     ("RCD" "Read Cards")
                     ("RCHA" "Reset and Load Channel A")
                     ("RCHB" "Reset and Load Channel B")
                     ("RCHC" "Reset and Load Channel C")
                     ("RCHD" "Reset and Load Channel D")
                     ("RCHE" "Reset and Load Channel E")
                     ("RCHF" "Reset and Load Channel F")
                     ("RCHG" "Reset and Load Channel G")
                     ("RCHH" "Reset and Load Channel H")
                     ("RCT" "Restore Channel Traps")
                     ("RDR" "Read Drum")
                     ("RDS" "Read Select")
                     ("RCDA" "Read Card Reader Channel A")
                     ("RDCA" "Reset Data Channel A")
                     ("REM" "Remarks" t)
                     ("REW" "Rewind")
                     ("REWA" "Rewind Channel A")
                     ("RFT" "Right Half Indicators OFF Test")
                     ("RIA" "Reset Indicators from Accumulator")
                     ("RIC")
                     ("RIL" "Reset Indicators of Left Half")
                     ("RIR" "Reset Indicators of Right Half")
                     ("RIS" "Reset Indicators from Storage")
                     ("RND" "Round")
                     ("RNT" "Right Half Indicators ON Test")
                     ("RPR" "Read Printer")
                     ("RPRA" "Read Printer Channel A")
                     ("RQL" "Rotate MQ Left")
                     ("RSCA" "Reset and Start Channel A")
                     ("RSCB" "Reset and Start Channel B")
                     ("RSCC" "Reset and Start Channel C")
                     ("RSCD" "Reset and Start Channel D")
                     ("RSCE" "Reset and Start Channel E")
                     ("RSCF" "Reset and Start Channel F")
                     ("RSCG" "Reset and Start Channel G")
                     ("RSCH" "Reset and Start Channel H")
                     ("RTB" "Read Tape Binary")
                     ("RTBA" "Read Tape Binary Channel A")
                     ("RTD" "Read Tape Decimal")
                     ("RTT" "Redundancy Tape Test")
                     ("RUN" "Rewind and Unload")
                     ("SBM" "Subtract Magnitude")
                     ("SCA" "Store Complement of Index in Address")
                     ("SCD" "Store Complement of Index in Decrement")
                     ("SCDA")
                     ("SCDB")
                     ("SCDC")
                     ("SCDD")
                     ("SCDE")
                     ("SCDF")
                     ("SCDG")
                     ("SCDH")
                     ("SCHA" "Store Channel A")
                     ("SCHB" "Store Channel B")
                     ("SCHC" "Store Channel C")
                     ("SCHD" "Store Channel D")
                     ("SCHE" "Store Channel E")
                     ("SCHF" "Store Channel F")
                     ("SCHG" "Store Channel G")
                     ("SCHH" "Store Channel H")
                     ("SDH")
                     ("SDL")
                     ("SDN" "Set Density")
                     ("SEA" )
                     ("SEB" )
                     ("SET" "Set Value of Symbol" t)
                     ("SIL" "Set Indicator of Left Half")
                     ("SIR" "Set Indicator of Right Half")
                     ("SLF" "Sense Lights Off")
                     ("SLN" "Sense Lights On")
                     ("SLQ" "Store Left Half MQ")
                     ("SLT" "Sense Light Test")
                     ("SLW" "Store Logical Word")
                     ("SMS")
                     ("SNS")
                     ("SPACE" "Space Listing" t)
                     ("SPR" "Sense Printer")
                     ("SPRA" "Sense Printer Channel A")
                     ("SPT" "Sense Printer Test")
                     ("SPU" "Sense Punch")
                     ("SSLA")
                     ("SSLB")
                     ("SSLC")
                     ("SSLD")
                     ("SSLE")
                     ("SSLF")
                     ("SSLG")
                     ("SSLH")
                     ("SSM" "Set Sign Minus")
                     ("SSP" "Set Sign Plus")
                     ("STA" "Store Address")
                     ("STCA" "Start Channel A")
                     ("STCB" "Start Channel B")
                     ("STCC" "Start Channel C")
                     ("STCD" "Start Channel D")
                     ("STCE" "Start Channel E")
                     ("STCF" "Start Channel F")
                     ("STCG" "Start Channel G")
                     ("STCH" "Start Channel H")
                     ("STD" "Store Decrement")
                     ("STI" "Store Indicators")
                     ("STL" "Store Instruction Location Counter")
                     ("STO" "Store")
                     ("STP" "Store Prefix")
                     ("STQ" "Store MQ")
                     ("STR" "Store Location and Trap")
                     ("STT" "Store Tag")
                     ("STZ" "Store Zero")
                     ("SUB" "Subtract")
                     ("SVN")
                     ("SWT" "Sense Switch Test")
                     ("SXA" "Store Index in Address")
                     ("SXD" "Store Index in Decrement")
                     ("SYN" "Define Synonym" t)
                     ("TAPENO" "Define Tape Number" t)
                     ("TCD" "Produce Binary Transfer Card" t)
                     ("TCH")
                     ("TCM")
                     ("TCNA" "Transfer on Disk A Not in Operation")
                     ("TCNB" "Transfer on Disk B Not in Operation")
                     ("TCNC" "Transfer on Disk C Not in Operation")
                     ("TCND" "Transfer on Disk D Not in Operation")
                     ("TCNE" "Transfer on Disk E Not in Operation")
                     ("TCNF" "Transfer on Disk F Not in Operation")
                     ("TCNG" "Transfer on Disk G Not in Operation")
                     ("TCNH" "Transfer on Disk H Not in Operation")
                     ("TCOA" "Transfer on Disk A in Operation")
                     ("TCOB" "Transfer on Disk B in Operation")
                     ("TCOC" "Transfer on Disk C in Operation")
                     ("TCOD" "Transfer on Disk D in Operation")
                     ("TCOE" "Transfer on Disk E in Operation")
                     ("TCOF" "Transfer on Disk F in Operation")
                     ("TCOG" "Transfer on Disk G in Operation")
                     ("TCOH" "Transfer on Disk H in Operation")
                     ("TDC")
                     ("TEFA" "Transfer on Disk A End of File")
                     ("TEFB" "Transfer on Disk B End of File")
                     ("TEFC" "Transfer on Disk C End of File")
                     ("TEFD" "Transfer on Disk D End of File")
                     ("TEFE" "Transfer on Disk E End of File")
                     ("TEFF" "Transfer on Disk F End of File")
                     ("TEFG" "Transfer on Disk G End of File")
                     ("TEFH" "Transfer on Disk H End of File")
                     ("TIF" "Transfer if Indicators Off")
                     ("TIO" "Transfer if Indicators On")
                     ("TITLE" "Abbreviate Listing" t)
                     ("TIX" "Transfer on Index")
                     ("TLQ" "Transfer on Low MQ")
                     ("TMI" "Transfer on Minus")
                     ("TNO" "Transfer on No Overflow")
                     ("TNX" "Transfer on No Index")
                     ("TNZ" "Transfer on No Zero")
                     ("TOV" "Transfer on Overflow")
                     ("TPL" "Transfer on Plus")
                     ("TQO" "Transfer on MQ Overflow")
                     ("TQP" "Transfer on MQ Plus")
                     ("TRA" "Transfer")
                     ("TRCA" "Transfer on Disk A Redundancy Check")
                     ("TRCB" "Transfer on Disk B Redundancy Check")
                     ("TRCC" "Transfer on Disk C Redundancy Check")
                     ("TRCD" "Transfer on Disk D Redundancy Check")
                     ("TRCE" "Transfer on Disk E Redundancy Check")
                     ("TRCF" "Transfer on Disk F Redundancy Check")
                     ("TRCG" "Transfer on Disk G Redundancy Check")
                     ("TRCH" "Transfer on Disk H Redundancy Check")
                     ("TSX" "Transfer and Set Index")
                     ("TTL" "Set Title of Listing" t)
                     ("TTR" "Trap Transfer")
                     ("TWT")
                     ("TXH" "Transfer on Index High")
                     ("TXI" "Transfer with Index Incremented")
                     ("TXL" "Transfer on Index Low or Equal")
                     ("TZE" "Transfer on Zero")
                     ("UAM" "Unnormalized Add Magnitude")
                     ("UFA" "Unnormalized Floating Add")
                     ("UFM" "Unnormalized Floating Multiply")
                     ("UFS" "Unnormalized Floating Subtract")
                     ("UNLIST" "Disable Listing")
                     ("USM" "Unnormalized Subtract Magnitude")
                     ("VDH" "Variable Length Divide or Halt")
                     ("VDP" "Variable Length Divide or Proceed")
                     ("VFD" "Variable-width Field Data" t)
                     ("VLM" "Variable Length Multiply")
                     ("WDR")
                     ("WEF" "Write End of File")
                     ("WEFA" "Write End of File Channel A")
                     ("WPB" "Write Printer Binary")
                     ("WPD" "Write Printer Decimal")
                     ("WPDA" "Write Printer Decimal Channel A")
                     ("WPR")
                     ("WPU")
                     ("WPUA" "Write Punch Channel A")
                     ("WRS" "Write Select")
                     ("WTB" "Write Tape Binary")
                     ("WTBA" "Write Tape Binary Channel A")
                     ("WTD" "Write Tape Decimal")
                     ("WTR")
                     ("WTV")
                     ("XCA" "Exchange Accumulator and MQ")
                     ("XCL" "Exchange Logical Accumulator and MQ")
                     ("XEC" "Execute")
                     ("XIT")
                     ("XMT")
                     ("ZAC")
                     ("ZET" "Storage Zero Test")
                     ("ZSA")
                     ("ZSD"))))))